baseURL = 'https://manuellevi.com/'
# disablePathToLower = true
languageCode = 'en-us'
title = 'Manuel Levi'

theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true